apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
  labels:
    app: was
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: 533616270150.dkr.ecr.ap-northeast-2.amazonaws.com/70491-was:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: was-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: was
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
